# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9qHH5-Mfh8MDlxJ7-Zg92VIoenuuKmO
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from google.colab import files
uploaded = files.upload()
student= pd.read_csv('student_scores.csv')
# print(df_students)
# print(df_students.isnull().sum())
# clean = df_students.dropna()
# print(clean)
# print(clean.isnull().sum())
# print(df_students.fillna(0))
# column=(df_students.columns)
# df_students.columns = df_students.columns.str.lower().str.strip().drop_duplicates()
# print(df_students.columns)
# df_students = df_students.duplicated().sum()
# print(df_students)
student= student.drop_duplicates().fillna(0)
student.columns= student.columns.str.strip().str.lower()
student= student.rename(columns={"Name" : "Identifier"})
print(student)
student.to_csv("Completed task 1.csv", index=False)
from google.colab import files
files.download("Completed task 1.csv")